name: Secvisogram CI

on:
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - uses: actions/setup-node@v3
        with:
          node-version: '16.16.0'
      - run: npm ci
      - run: npx eslint --max-warnings 0
      - run: npm run-script build
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - uses: actions/setup-node@v3
        with:
          node-version: '16.16.0'
      - run: npm ci
      - run: sudo apt-get install xvfb
      - run: npm run dev &
      - uses: ifaxity/wait-on-action@v1
        with:
          delay: 1
          timeout: 30000
          resource: tcp:localhost:8080
      - run: xvfb-run --auto-servernum npm run-script test
